// <auto-generated />
using FantasyLEC.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FantasyLEC.Core.Migrations
{
    [DbContext(typeof(FantasyLecDbContext))]
    [Migration("20210306130942_AddTeamAndPlayer")]
    partial class AddTeamAndPlayer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("FantasyLEC.Core.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("AveragePoints")
                        .HasColumnType("double precision");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SummonerName")
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerName")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 90,
                            AveragePoints = 0.0,
                            CountryCode = "de",
                            FirstName = "Janik",
                            Image = "http://static.lolesports.com/players/SK_JENAX.png",
                            LastName = "Bartels",
                            Role = 0,
                            SummonerName = "Jenax",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 91,
                            AveragePoints = 0.0,
                            CountryCode = "dk",
                            FirstName = "Kristian",
                            Image = "http://static.lolesports.com/players/SK_TYNX.png",
                            LastName = "Østergaard Hansen",
                            Role = 1,
                            SummonerName = "TynX",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 93,
                            AveragePoints = 0.0,
                            CountryCode = "fr",
                            FirstName = "Jean",
                            Image = "http://static.lolesports.com/players/SK_JEZU.png",
                            LastName = "Massol",
                            Role = 3,
                            SummonerName = "Jezu",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 94,
                            AveragePoints = 0.0,
                            CountryCode = "se",
                            FirstName = "Erik",
                            Image = "http://static.lolesports.com/players/SK_TREATZ.png",
                            LastName = "Wessén",
                            Role = 4,
                            SummonerName = "Treatz",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 92,
                            AveragePoints = 0.0,
                            CountryCode = "be",
                            FirstName = "Ersin",
                            Image = "http://static.lolesports.com/players/SK_BLUE.png",
                            LastName = "Gören",
                            Role = 2,
                            SummonerName = "Blue",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 62,
                            AveragePoints = 0.0,
                            CountryCode = "no",
                            FirstName = "Erlend",
                            Image = "http://static.lolesports.com/players/AST_NUKEDUCK.png",
                            LastName = "Holm",
                            Role = 2,
                            SummonerName = "nukeduck",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 60,
                            AveragePoints = 0.0,
                            CountryCode = "fi",
                            FirstName = "Matti",
                            Image = "http://static.lolesports.com/players/AST_WHITEKNIGHT.png",
                            LastName = "Sormunen",
                            Role = 0,
                            SummonerName = "WhiteKnight",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 61,
                            AveragePoints = 0.0,
                            CountryCode = "ru",
                            FirstName = "Nikolay",
                            Image = "http://static.lolesports.com/players/AST_ZANZARAH.png",
                            LastName = "Akatov",
                            Role = 1,
                            SummonerName = "Zanzarah",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 63,
                            AveragePoints = 0.0,
                            CountryCode = "se",
                            FirstName = "Jesper Klarin",
                            Image = "http://static.lolesports.com/players/AST_JESKLA.png",
                            LastName = "Stromberg",
                            Role = 3,
                            SummonerName = "Jeskla",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 64,
                            AveragePoints = 0.0,
                            CountryCode = "se",
                            FirstName = "Hampus",
                            Image = "http://static.lolesports.com/players/AST_PROMISQ.png",
                            LastName = "Abrahamsson",
                            Role = 4,
                            SummonerName = "promisq",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 67,
                            AveragePoints = 0.0,
                            CountryCode = "se",
                            FirstName = "Felix",
                            Image = "https://lolstatic-a.akamaihd.net/esports-assets/production/player/magifelix-f98zv79q.png",
                            LastName = "Boström",
                            Role = 2,
                            SummonerName = "MagiFelix",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 73,
                            AveragePoints = 0.0,
                            CountryCode = "cz",
                            FirstName = "Patrik",
                            Image = "http://static.lolesports.com/players/XL_PATRIK.png",
                            LastName = "Jiru",
                            Role = 3,
                            SummonerName = "Patrik",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 74,
                            AveragePoints = 0.0,
                            CountryCode = "no",
                            FirstName = "Tore",
                            Image = "http://static.lolesports.com/players/XL_TORE.png",
                            LastName = "Hoel Eilertsen",
                            Role = 4,
                            SummonerName = "Tore",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 70,
                            AveragePoints = 0.0,
                            CountryCode = "se",
                            FirstName = "Felix",
                            Image = "http://static.lolesports.com/players/XL_KRYZE.png",
                            LastName = "Hellström",
                            Role = 0,
                            SummonerName = "Kryze",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 71,
                            AveragePoints = 0.0,
                            CountryCode = "gb",
                            FirstName = "Daniel",
                            Image = "http://static.lolesports.com/players/XL_DAN.png",
                            LastName = "Hockley",
                            Role = 1,
                            SummonerName = "Dan",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 72,
                            AveragePoints = 0.0,
                            CountryCode = "pl",
                            FirstName = "Pavel",
                            Image = "http://static.lolesports.com/players/XL_CZEKOLAD.png",
                            LastName = "Szczepanik",
                            Role = 2,
                            SummonerName = "Czekolad",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 32,
                            AveragePoints = 0.0,
                            CountryCode = "se",
                            FirstName = "Emil",
                            Image = "http://static.lolesports.com/players/RGE_LARSSEN.png",
                            LastName = "Larsson",
                            Role = 2,
                            SummonerName = "Larssen",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 31,
                            AveragePoints = 0.0,
                            CountryCode = "pl",
                            FirstName = "Kacper",
                            Image = "http://static.lolesports.com/players/RGE_INSPIRED.png",
                            LastName = "Sloma",
                            Role = 1,
                            SummonerName = "Inspired",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 33,
                            AveragePoints = 0.0,
                            CountryCode = "fr",
                            FirstName = "Steven",
                            Image = "http://static.lolesports.com/players/RGE_HANS_SAMA.png",
                            LastName = "Liv",
                            Role = 3,
                            SummonerName = "Hans sama",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 30,
                            AveragePoints = 0.0,
                            CountryCode = "ro",
                            FirstName = "Andrei",
                            Image = "http://static.lolesports.com/players/RGE_ODOAMNE.png",
                            LastName = "Pascu",
                            Role = 0,
                            SummonerName = "Odoamne",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 34,
                            AveragePoints = 0.0,
                            CountryCode = "pl",
                            FirstName = "Adrian",
                            Image = "http://static.lolesports.com/players/RGE_TRYMBI.png",
                            LastName = "Trybus",
                            Role = 4,
                            SummonerName = "Trymbi",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 42,
                            AveragePoints = 0.0,
                            CountryCode = "cz",
                            FirstName = " Marek",
                            Image = "http://static.lolesports.com/players/MAD_Humanoid.png",
                            LastName = "Brázda",
                            Role = 2,
                            SummonerName = "Humanoid",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 43,
                            AveragePoints = 0.0,
                            CountryCode = "cz",
                            FirstName = "Matyáš",
                            Image = "http://static.lolesports.com/players/MAD_Carzzy.png",
                            LastName = "Orság",
                            Role = 3,
                            SummonerName = "Carzzy",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 44,
                            AveragePoints = 0.0,
                            CountryCode = "de",
                            FirstName = "Norman",
                            Image = "http://static.lolesports.com/players/MAD_Kaiser.png",
                            LastName = "Kaiser",
                            Role = 4,
                            SummonerName = "Kaiser",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 40,
                            AveragePoints = 0.0,
                            CountryCode = "tr",
                            FirstName = "İrfan",
                            Image = "http://static.lolesports.com/players/MAD_Armut.png",
                            LastName = "Tükek",
                            Role = 0,
                            SummonerName = "Armut",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 41,
                            AveragePoints = 0.0,
                            CountryCode = "es",
                            FirstName = "Javier",
                            Image = "http://static.lolesports.com/players/MAD_Elyoya.png",
                            LastName = "Prades",
                            Role = 1,
                            SummonerName = "Elyoya",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 24,
                            AveragePoints = 0.0,
                            CountryCode = "bg",
                            FirstName = "Zdravets",
                            Image = "http://static.lolesports.com/players/FNC_HYLISSANG.png",
                            LastName = "Iliev Galabov",
                            Role = 4,
                            SummonerName = "Hylissang",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 20,
                            AveragePoints = 0.0,
                            CountryCode = "be",
                            FirstName = "Gabriel",
                            Image = "http://static.lolesports.com/players/FNC_BWIPO.png",
                            LastName = "Rau",
                            Role = 0,
                            SummonerName = "Bwipo",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 21,
                            AveragePoints = 0.0,
                            CountryCode = "pl",
                            FirstName = "Oskar",
                            Image = "http://static.lolesports.com/players/FNC_SELFMADE.png",
                            LastName = "Boderek",
                            Role = 1,
                            SummonerName = "Selfmade",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 22,
                            AveragePoints = 0.0,
                            CountryCode = "be",
                            FirstName = "Yasin",
                            Image = "http://static.lolesports.com/players/FNC_NISQY.png",
                            LastName = "Dincer",
                            Role = 2,
                            SummonerName = "Nisqy",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 23,
                            AveragePoints = 0.0,
                            CountryCode = "de",
                            FirstName = "Elias",
                            Image = "http://static.lolesports.com/players/FNC_UPSET.png",
                            LastName = "Lipp",
                            Role = 3,
                            SummonerName = "Upset",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 11,
                            AveragePoints = 0.0,
                            CountryCode = "pl",
                            FirstName = "Marcin",
                            Image = "http://static.lolesports.com/players/G2_JANKOS.png",
                            LastName = "Jankowski",
                            Role = 1,
                            SummonerName = "Jankos",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            AveragePoints = 0.0,
                            CountryCode = "dk",
                            FirstName = "Martin",
                            Image = "http://static.lolesports.com/players/G2_WUNDER.png",
                            LastName = "Hansen",
                            Role = 0,
                            SummonerName = "Wunder",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 14,
                            AveragePoints = 0.0,
                            CountryCode = "si",
                            FirstName = "Mihael",
                            Image = "http://static.lolesports.com/players/G2_MICKYX.png",
                            LastName = "Mehle",
                            Role = 4,
                            SummonerName = "Mikyx",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 12,
                            AveragePoints = 0.0,
                            CountryCode = "dk",
                            FirstName = "Rasmus",
                            Image = "http://static.lolesports.com/players/G2_CAPS.png",
                            LastName = "Winther",
                            Role = 2,
                            SummonerName = "Caps",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 13,
                            AveragePoints = 0.0,
                            CountryCode = "se",
                            FirstName = "Martin",
                            Image = "http://static.lolesports.com/players/G2_REKKLES.png",
                            LastName = "Larsson",
                            Role = 3,
                            SummonerName = "Rekkles",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 81,
                            AveragePoints = 0.0,
                            CountryCode = "es",
                            FirstName = "Iván",
                            Image = "http://static.lolesports.com/players/MSF_RAZORK.png",
                            LastName = "Martín",
                            Role = 1,
                            SummonerName = "Razork",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 89,
                            AveragePoints = 0.0,
                            CountryCode = "cz",
                            FirstName = "Petr",
                            Image = "http://static.lolesports.com/players/MSF_DENYK.png",
                            LastName = "Haramach",
                            Role = 4,
                            SummonerName = "denyk",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 83,
                            AveragePoints = 0.0,
                            CountryCode = "dk",
                            FirstName = "Kasper",
                            Image = "http://static.lolesports.com/players/MSF_KOBBE.png",
                            LastName = "Kobberup",
                            Role = 3,
                            SummonerName = "Kobbe",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 85,
                            AveragePoints = 0.0,
                            CountryCode = "pl",
                            FirstName = "Tobiasz",
                            Image = "http://static.lolesports.com/players/MSF_AGRESIVOO.png",
                            LastName = "Ciba",
                            Role = 0,
                            SummonerName = "Agresivoo",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 80,
                            AveragePoints = 0.0,
                            CountryCode = "kr",
                            FirstName = "Shin",
                            Image = "http://static.lolesports.com/players/MSF_HIRIT.png",
                            LastName = "Tae-min",
                            Role = 0,
                            SummonerName = "HiRit",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 82,
                            AveragePoints = 0.0,
                            CountryCode = "fr",
                            FirstName = "Vincent",
                            Image = "http://static.lolesports.com/players/MSF_VETHEO.png",
                            LastName = "Berrié",
                            Role = 2,
                            SummonerName = "Vetheo",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 84,
                            AveragePoints = 0.0,
                            CountryCode = "pl",
                            FirstName = "Oskar",
                            Image = "http://static.lolesports.com/players/MSF_VANDER.png",
                            LastName = "Bogdan",
                            Role = 4,
                            SummonerName = "Vander",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 52,
                            AveragePoints = 0.0,
                            CountryCode = "de",
                            FirstName = "Felix",
                            Image = "http://static.lolesports.com/players/S04_Abbedagge.png",
                            LastName = "Braun",
                            Role = 2,
                            SummonerName = "Abbedagge",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 53,
                            AveragePoints = 0.0,
                            CountryCode = "sk",
                            FirstName = "Matus",
                            Image = "http://static.lolesports.com/players/S04_Neon.png",
                            LastName = "Jakubcik",
                            Role = 3,
                            SummonerName = "Neon",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 51,
                            AveragePoints = 0.0,
                            CountryCode = "de",
                            FirstName = "Erberk",
                            Image = "http://static.lolesports.com/players/S04_Gilius.png",
                            LastName = "Demir",
                            Role = 1,
                            SummonerName = "Gilius",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 50,
                            AveragePoints = 0.0,
                            CountryCode = "de",
                            FirstName = "Sergen",
                            Image = "http://static.lolesports.com/players/S04_BrokenBlade.png",
                            LastName = "Çelik",
                            Role = 0,
                            SummonerName = "BrokenBlade",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 54,
                            AveragePoints = 0.0,
                            CountryCode = "hr",
                            FirstName = "Dino",
                            Image = "http://static.lolesports.com/players/S04_Limit.png",
                            LastName = "Tot",
                            Role = 4,
                            SummonerName = "LIMIT",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 101,
                            AveragePoints = 0.0,
                            CountryCode = "fr",
                            FirstName = "Duncan",
                            Image = "http://static.lolesports.com/players/VIT_SKEANZ.png",
                            LastName = "Marquet",
                            Role = 1,
                            SummonerName = "Skeanz",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 108,
                            AveragePoints = 0.0,
                            CountryCode = "gr",
                            FirstName = "Markos",
                            Image = "http://static.lolesports.com/players/VIT_COMP.png",
                            LastName = "Stamkopoulos",
                            Role = 3,
                            SummonerName = "Comp",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 102,
                            AveragePoints = 0.0,
                            CountryCode = "rs",
                            FirstName = "Aljoša",
                            Image = "http://static.lolesports.com/players/VIT_MILICA.png",
                            LastName = "Kovandžić",
                            Role = 2,
                            SummonerName = "Milica",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 104,
                            AveragePoints = 0.0,
                            CountryCode = "gr",
                            FirstName = "Labros",
                            Image = "http://static.lolesports.com/players/VIT_LABROV.png",
                            LastName = "Papoutsakis",
                            Role = 4,
                            SummonerName = "Labrov",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 100,
                            AveragePoints = 0.0,
                            CountryCode = "dk",
                            FirstName = "Mathias",
                            Image = "http://static.lolesports.com/players/VIT_SZYGENDA.png",
                            LastName = "Jensen",
                            Role = 0,
                            SummonerName = "Szygenda",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 103,
                            AveragePoints = 0.0,
                            CountryCode = "si",
                            FirstName = "Jus",
                            Image = "http://static.lolesports.com/players/1591899881632_Ju-CROWNSHOT-Marui-1.png",
                            LastName = "Marusic",
                            Role = 3,
                            SummonerName = "Crownshot",
                            TeamId = 10
                        });
                });

            modelBuilder.Entity("FantasyLEC.Core.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<double>("AveragePoints")
                        .HasColumnType("double precision");

                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            AveragePoints = 0.0,
                            Code = "SK",
                            Image = "http://static.lolesports.com/teams/SK_FullColor.png",
                            Name = "SK Gaming"
                        },
                        new
                        {
                            Id = 6,
                            AveragePoints = 0.0,
                            Code = "AST",
                            Image = "http://static.lolesports.com/teams/AST-FullonDark.png",
                            Name = "Astralis"
                        },
                        new
                        {
                            Id = 7,
                            AveragePoints = 0.0,
                            Code = "XL",
                            Image = "http://static.lolesports.com/teams/Excel_FullColor2.png",
                            Name = "EXCEL Esports"
                        },
                        new
                        {
                            Id = 3,
                            AveragePoints = 0.0,
                            Code = "RGE",
                            Image = "http://static.lolesports.com/teams/Rogue_FullColor2.png",
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 4,
                            AveragePoints = 0.0,
                            Code = "MAD",
                            Image = "http://static.lolesports.com/teams/1592591395339_MadLionsMAD-01-FullonDark.png",
                            Name = "MAD Lions"
                        },
                        new
                        {
                            Id = 2,
                            AveragePoints = 0.0,
                            Code = "FNC",
                            Image = "http://static.lolesports.com/teams/1592591295307_FnaticFNC-01-FullonDark.png",
                            Name = "Fnatic"
                        },
                        new
                        {
                            Id = 1,
                            AveragePoints = 0.0,
                            Code = "G2",
                            Image = "http://static.lolesports.com/teams/G2-FullonDark.png",
                            Name = "G2 Esports"
                        },
                        new
                        {
                            Id = 8,
                            AveragePoints = 0.0,
                            Code = "MSF",
                            Image = "http://static.lolesports.com/teams/1592591419157_MisfitsMSF-01-FullonDark.png",
                            Name = "Misfits Gaming"
                        },
                        new
                        {
                            Id = 5,
                            AveragePoints = 0.0,
                            Code = "S04",
                            Image = "http://static.lolesports.com/teams/S04_Standard_Logo1.png",
                            Name = "FC Schalke 04 Esports"
                        },
                        new
                        {
                            Id = 10,
                            AveragePoints = 0.0,
                            Code = "VIT",
                            Image = "http://static.lolesports.com/teams/1592591570387_VitalityVIT-01-FullonDark.png",
                            Name = "Team Vitality"
                        });
                });

            modelBuilder.Entity("FantasyLEC.Core.Models.Player", b =>
                {
                    b.HasOne("FantasyLEC.Core.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyLEC.Core.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
